Add week 1
Dev-incubator/WebAutoparkArtem2 pull request #1
Opened 2021-06-20 08:46 UTC by PWMaestro

Create IRepository interface.
Apply this interface to Vehicles, VehiclesTypes, Spares tables.

2021-06-20 11:49 UTC, dzmitri-litvinov approved these changes

2021-06-20 14:21 UTC, PushMeNow requested changes

2021-06-22 18:21 UTC, UNDogMan commented on DataAccessLayer/Repositories/RepositoryBase.cs
> +        public ValueTask DisposeAsync() => connection.DisposeAsync();
is ? operator not enough?

2021-06-22 18:39 UTC, UNDogMan requested changes
Fix Column names. Must be same to Entity Properties.

2021-06-28 17:32 UTC, UNDogMan approved these changes
Approve

2021-06-28 17:39 UTC, PushMeNow approved these changes

2021-06-28 17:39 UTC, merged