Add week-2
Dev-incubator/WebAutoparkArtem2 pull request #5
Opened 2021-07-02 07:30 UTC by PWMaestro

Add entity:
* order
* orderElement

Create repositories:
* orderRepository
* orderElementsRepository

Add repos to dependency injection.
Add connection string to DB.

2021-07-02 08:12 UTC, PushMeNow requested changes

2021-07-02 08:12 UTC, PushMeNow commented on DataAccessLayer/Entities/Order.cs
> +        public int Id { get; set; }
In c# practice usually all ids are naming together their entity name, example OrderId. Don't use pls name just Id it is confusing name.

2021-07-02 08:12 UTC, PushMeNow commented on DataAccessLayer/Repositories/OrderElementsRepository.cs
> +                                       + "VALUES                    (@OrderId, @SpareId, @SpareQuantity)";
Wait why is here so huge tab between VALUES and params?

2021-07-03 07:44 UTC, PushMeNow approved these changes

2021-07-03 08:08 UTC, dzmitri-litvinov approved these changes

2021-07-09 11:15 UTC, merged