Week-3
Dev-incubator/WebAutoparkArtem2 pull request #6
Opened 2021-07-09 19:33 UTC by PWMaestro

Create:
* web page for spares
* web page for vehicle types
* fix some dapper requests

2021-07-10 07:37 UTC, dbogdan2000 approved these changes

2021-07-10 07:37 UTC, dbogdan2000 approved these changes

2021-07-10 07:37 UTC, dbogdan2000 approved these changes

2021-07-16 19:02 UTC, PushMeNow requested changes

2021-07-23 17:43 UTC, dbogdan2000 approved these changes

2021-07-24 17:13 UTC, PushMeNow requested changes

2021-07-24 17:13 UTC, PushMeNow commented on WebAutopark/Views/Spare/Create.cshtml
> +﻿@{
Model?

2021-07-24 17:13 UTC, PushMeNow commented on WebAutopark/Views/Spare/Update.cshtml
> +</form>
Use html helpers or tag helpers

2021-07-24 17:13 UTC, PushMeNow commented on WebAutopark/Views/Spare/Create.cshtml
> +</form>
Html/tag helpers

2021-07-24 17:13 UTC, PushMeNow commented on WebAutopark/Views/VehicleType/Update.cshtml
> +        new { @value = Model.TypeName }
Why do you need @value here? It is redundant when you are using html helpers because value is getting form model automatically.

2021-07-27 10:02 UTC, PushMeNow approved these changes

2021-07-27 10:03 UTC, merged